name: "Daily Download Job"
on:
  schedule:
    - cron:  "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:
env:
  FILE_DIR: /tmp/out
jobs:
  daily_scrape:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
          cache: "pip"
      - name: "Install python deps"
        run: pip install -r requirements.txt
      - name: "Run scraper for shufersal"
        working-directory: ./price_scrapers
        run: scrapy crawl shufersal

      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: "Merge outputs"
        working-directory: {{ env.FILE_DIR}}/full
        run: 'cat *.gz > "$NOW"_shufersal.gz'

      - uses: actions/upload-artifact@v3
        with:
          name: {{ env.NOW }}_shufersal.gz
          path: {{ env.FILE_DIR}}/full/{{ env.NOW }}_shufersal.gz






